# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0002_slider'),
    ]

    operations = [
    ]
