# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0004_slider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('alternative', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NuField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('alternative', models.CharField(default='', max_length=300)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('default', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='alternative',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slider',
            name='alternative',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nufield',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDE.Block'),
        ),
        migrations.AddField(
            model_name='chfield',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDE.Block'),
        ),
        migrations.AddField(
            model_name='block',
            name='lib',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IDE.Lib'),
        ),
    ]
