# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0006_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='code',
            field=models.TextField(verbose_name='code'),
        ),
    ]
